#!/bin/sh

NCUSER=admin
NCPASSWD=admin
NCHOST=localhost
NCPORT=2022

echo ... cmd-edit-config-mef-topology-modify.xml
netconf-console -u $NCUSER -p $NCPASSWD --host $NCHOST --port $NCPORT -v 1.0 -s pretty ../mef/netconf/cmd-edit-config-mef-topology-modify.xml
echo ... cmd-edit-config-mef-global-modify.xml
netconf-console -u $NCUSER -p $NCPASSWD --host $NCHOST --port $NCPORT -v 1.0 -s pretty ../mef/netconf/cmd-edit-config-mef-global-modify.xml
echo ... cmd-edit-config-mef-epl01-modify.xml
netconf-console -u $NCUSER -p $NCPASSWD --host $NCHOST --port $NCPORT -v 1.0 -s pretty ../mef/netconf/cmd-edit-config-mef-epl01-modify.xml
echo ... cconfig-mef-eplan01-modify.xml
netconf-console -u $NCUSER -p $NCPASSWD --host $NCHOST --port $NCPORT -v 1.0 -s pretty ../mef/netconf/cmd-edit-config-mef-eplan01-modify.xml
echo ... cmd-edit-config-mef-eptree01-modify.xml
netconf-console -u $NCUSER -p $NCPASSWD --host $NCHOST --port $NCPORT -v 1.0 -s pretty ../mef/netconf/cmd-edit-config-mef-eptree01-modify.xml
echo ... cmd-edit-config-mef-evpl01-modify.xml
netconf-console -u $NCUSER -p $NCPASSWD --host $NCHOST --port $NCPORT -v 1.0 -s pretty ../mef/netconf/cmd-edit-config-mef-evpl01-modify.xml
echo ... cmd-edit-config-mef-evplan01-modify.xml
netconf-console -u $NCUSER -p $NCPASSWD --host $NCHOST --port $NCPORT -v 1.0 -s pretty ../mef/netconf/cmd-edit-config-mef-evplan01-modify.xml
echo ... cmd-edit-config-mef-evptree01-modify.xml
netconf-console -u $NCUSER -p $NCPASSWD --host $NCHOST --port $NCPORT -v 1.0 -s pretty ../mef/netconf/cmd-edit-config-mef-evptree01-modify.xml
