#!/bin/sh

RESTCRED=admin:admin
RESTURL=http
NSOHOST=localhost
RESTPORT=10888

curl -u $RESTCRED  -H "Accept:application/vnd.yang.data+json" $RESTURL://$NSOHOST:$RESTPORT/api/operational/mef-topology?deep
curl -u $RESTCRED  -H "Accept:application/vnd.yang.data+json" $RESTURL://$NSOHOST:$RESTPORT/api/operational/mef-global?deep
curl -u $RESTCRED  -H "Accept:application/vnd.yang.data+json" $RESTURL://$NSOHOST:$RESTPORT/api/operational/mef-interfaces?deep
curl -u $RESTCRED  -H "Accept:application/vnd.yang.data+json" $RESTURL://$NSOHOST:$RESTPORT/api/operational/mef-services?deep

