#!/bin/sh

RESTCRED=admin:admin
RESTURL=https
NSOHOST=96.86.165.79
RESTPORT=10888
RESTSEC=-k

curl $RESTSEC -u $RESTCRED  -H "Accept:application/vnd.yang.data+json" $RESTURL://$NSOHOST:$RESTPORT/api/running/mef-topology?deep
curl $RESTSEC -u $RESTCRED  -H "Accept:application/vnd.yang.data+json" $RESTURL://$NSOHOST:$RESTPORT/api/running/mef-global?deep
curl $RESTSEC -u $RESTCRED  -H "Accept:application/vnd.yang.data+json" $RESTURL://$NSOHOST:$RESTPORT/api/running/mef-interfaces?deep
curl $RESTSEC -u $RESTCRED  -H "Accept:application/vnd.yang.data+json" $RESTURL://$NSOHOST:$RESTPORT/api/running/mef-services?deep

